# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 16:24
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_calificador', models.CharField(max_length=30)),
                ('rating', models.IntegerField(default=0)),
                ('rating_s', models.CharField(max_length=6)),
                ('fue_calificado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_cancion', models.CharField(max_length=500)),
                ('artista', models.CharField(max_length=250)),
                ('audio', models.FileField(default='', upload_to='')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_de_lista', models.CharField(max_length=500)),
                ('canciones', models.ManyToManyField(blank=True, to='MyMusic.Cancion')),
                ('user_list', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='calificacion',
            name='cancion_calificada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyMusic.Cancion'),
        ),
    ]
