# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 22:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyMusic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lista',
            old_name='cancion',
            new_name='canciones',
        ),
        migrations.RenameField(
            model_name='lista',
            old_name='titulo_lista',
            new_name='titulo_de_lista',
        ),
    ]
