# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 22:54
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyMusic', '0002_auto_20170308_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='user_list',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
