# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyMusic', '0003_auto_20170308_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='canciones',
            field=models.ManyToManyField(blank=True, null=True, to='MyMusic.Cancion'),
        ),
    ]
