# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyMusic', '0004_auto_20170309_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_calificador', models.CharField(max_length=30)),
                ('rating', models.IntegerField(default=0)),
                ('fue_calificado', models.BooleanField(default=False)),
                ('cancion_calificada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyMusic.Cancion')),
            ],
        ),
        migrations.AlterField(
            model_name='lista',
            name='canciones',
            field=models.ManyToManyField(blank=True, to='MyMusic.Cancion'),
        ),
    ]
