# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyMusic', '0005_auto_20170311_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='rating_s',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
